name: Deploy

on:
  pull_request:
  push:
    branches: [main]

jobs:
  preview:
    if: github.event_name == 'pull_request'
    uses: techdays-ai/.github/.github/workflows/reusable-worker-deploy.yml@main
    with:
      environment: preview
    secrets: inherit

  production:
    if: github.event_name == 'push'
    uses: techdays-ai/.github/.github/workflows/reusable-worker-deploy.yml@main
    with:
      environment: production
    secrets: inherit
